baseURL = "https://mikaelsouza.com"
languageCode = "pt"
title = "Blog do Mikael"
theme = "notepadium"
enableRobotsTXT = true

#disqusShortname = "mikaslanche"

[params]
style = "dark"  # default: "auto", based on system. "light": light theme, "dark": dark theme.
#dateFormat = "Monday, January 2, 2006"
dateFormat = "02/01/2006"

[params.comments]
#enable = true

[params.math]
math = "on"  # true means globally, or on a per page set "math = true"
use = "katex"  # "mathjax" or "katex"

[params.syntax]
use = "none"  # builtin: "prismjs", "hljs". "none" means Chroma
theme = "xcode"
darkTheme = "xcode-dark"  # apply this theme in dark mode

#[params.share]
#enable = true
#addThisId = ""
#inlineToolId = ""

#[params.nav]
#showCategories = true       # /categories/
#showTags = true             # /tags/

# custom navigation items

#[[params.nav.custom]]
#title = "About"
#url = "/about"

#[[params.nav.custom]]
#title = "Hugo"
#url = "https://gohugo.io/"

